In [ ]:
# 1. Using the iris data set implement the KNN algorithm. Take different values for Test and training
# data set .Also use different values for k. Also find the accuracy level.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv("iris.csv")
# print(dataset)
# dataset.info()

x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,4].values

# print(x)
# print(y)

In [2]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

# print(x_test)

In [3]:
# from sklearn.preprocessing import StandardScaler
# scaler = StandardScaler()
# scaler.fit(x_train)

# x_train = scaler.transform(x_train)
# x_test = scaler.transform(x_test)

# print(x_train)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [6]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import accuracy_score
accuracy =accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

Accuracy: 0.9333333333333333


In [7]:
for (i,j) in zip(y_pred,y_test):
    if i!=j:
        print("Actual value:",i,"Predicted value:",j)
      
print("Number of mislabeled points from test data set:",(y_test != y_pred).sum())

Actual value: Versicolor Predicted value: Virginica
Actual value: Versicolor Predicted value: Virginica
Number of mislabeled points from test data set: 2


In [8]:
y_pred = classifier.predict(x_test)
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))



[[ 8  0  0]
 [ 0 13  0]
 [ 0  2  7]]
              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00         8
  Versicolor       0.87      1.00      0.93        13
   Virginica       1.00      0.78      0.88         9

    accuracy                           0.93        30
   macro avg       0.96      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30

